services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - blueprint
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - blueprint

networks:
  blueprint:
